# Generated by Django 6.0.5 on 2026-05-27 20:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='0 = без ограничений. Для процентных купонов — максимальная скидка в €', max_digits=10, verbose_name='Макс. сумма скидки'),
        ),
    ]
